apps/docmanager/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	url(r'^add/?$', 'docmanager.views.add', name='doc_add'),
	url(r'^edit/(?P<doc_id>\d+)?$', 'docmanager.views.edit', name='doc_edit'),
	url(r'^', 'docmanager.views.list', name='doc_list'),
)

apps/userprofile/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	url(r'^(?P<user_id>\d+)/update/profile/?$', 'userprofile.views.update_user_profile', name='update_user_profile'),
	url(r'^', 'userprofile.views.index', name='userprofile_index'),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
	(r'^userprofile/', include('userprofile.urls')),
	(r'^files/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT } ),

	url(r'^a/', include('docmanager.urls')),
	url(r'^d/(?P<doc_id>\d+)?$', 'docmanager.views.serve', name='doc_serve'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^accounts/login/?$', 'django.contrib.auth.views.login', name="login"),
	url(r'^accounts/logout/?$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),

	url(r'^(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT+'/uploads/'  } ),

	(r'^robots\.txt$', direct_to_template,
		{ 	'template': 'robots.txt', 
			'mimetype': 'text/plain' }),
	(r'^humans\.txt$', direct_to_template,
		{ 	'template': 'humans.txt', 
			'mimetype': 'text/plain' }),
	(r'^template$', direct_to_template,
		{ 	'template': '_template.html', 
			'mimetype': 'text/html' }),
	(r'^$', direct_to_template,
		{ 	'template': 'index.html', 
			'mimetype': 'text/html' }),
)

apps/common/models.py
from django.db import models

class SoftDeleteManager(models.Manager):
	''' Use this manager to get objects that have a deleted field '''
	def get_query_set(self):
		return super(SoftDeleteManager, self).get_query_set().filter(deleted=False)
	def all_with_deleted(self):
		return super(SoftDeleteManager, self).get_query_set()
	def deleted_set(self):
		return super(SoftDeleteManager, self).get_query_set().filter(deleted=True)

class BaseModel(models.Model):
	date_created = models.DateTimeField(auto_now_add=True, db_index=True, null=True, blank=True)
	last_modified = models.DateTimeField(auto_now=True, db_index=True, null=True, blank=True)
	deleted = models.BooleanField(default = False, db_index=True)
	date_deleted = models.DateTimeField(null = True, blank = True, db_index=True)
	objects = SoftDeleteManager()

	class Meta:
		abstract = True
		
	def delete(self):
		from datetime import datetime
		
		self.deleted = True
		self.date_deleted = self.last_modified
		self.save()

apps/docmanager/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import os.path
from common.models import BaseModel

class Document(BaseModel):
	creator = models.ForeignKey(User,related_name='creator')
	category = models.ForeignKey('Category',related_name='category')
	last_edited_by = models.ForeignKey(User,related_name='lastedit_user')
	title = models.CharField(max_length = 100)
	document = models.FileField(upload_to=settings.UPLOAD_DIR)

	def __unicode__(self):
		return '%s' % self.title

	def filename(self):
		return os.path.basename(self.document.name)

class Category(BaseModel):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return '%s' % self.name

apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from common.models import BaseModel

GENDER_CHOICES = (
	('M', 'Male'),
	('F', 'Female'),
)

class UserProfile(BaseModel):
	user = models.ForeignKey(User)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
	
	def __unicode__(self):
		return '%s' % self.user
		
def create_userprofile(sender, instance, created, **kwargs):
	try:
		UserProfile.objects.get(user=instance)
	except:
		try:
			UserProfile.objects.create(user=instance)
		except:
			pass
post_save.connect(create_userprofile, sender=User)

apps/docmanager/forms.py
from django.forms import ModelForm
	
from docmanager.models import Document

class DocumentForm(ModelForm):
	class Meta:
		model = Document
		exclude = ('user','creator','last_edited_by','deleted','date_deleted')

apps/userprofile/forms.py
from django.forms import ModelForm

from userprofile.models import UserProfile

class UserProfileForm(ModelForm):
	class Meta:
		model = UserProfile
		fields = ('gender',)

apps/docmanager/views.py
from django.template import RequestContext
from django.http import HttpResponseForbidden, HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.contrib.auth.models import User
from django.utils.encoding import smart_str
import os

from userprofile.models import UserProfile
from userprofile.forms import UserProfileForm
from docmanager.forms import DocumentForm
from docmanager.models import Document

def serve(request, doc_id=None):
	doc = Document.objects.get(pk=doc_id)
	return HttpResponseRedirect('/%s' % doc.filename())

@login_required
def list(request):
	documents = Document.objects.all().order_by('-last_modified')

	return render_to_response('list.html', {
		'documents': documents,
	}, context_instance=RequestContext(request))

@login_required
def add(request):
	if request.POST:
		form = DocumentForm(request.POST, request.FILES)
		if form.is_valid():
			f = form.save(commit=False)
			f.creator = request.user
			f.last_edited_by = request.user
			f.save()
			return HttpResponseRedirect('/a/add/')
	else:
		lastdoc = Document.objects.all().order_by('-last_modified')[:1]
		form = DocumentForm(initial={'category':lastdoc[0].category})
	return render_to_response('add.html', {
		'form': form,
	}, context_instance=RequestContext(request))

@login_required
def edit(request, doc_id=None):
	doc = Document.objects.get(pk=doc_id)
	if request.POST:
		if request.FILES and doc.document:
				os.remove(doc.document.path)
				doc.document.delete()
		form = DocumentForm(instance=doc,data=request.POST,files=request.FILES)
		if form.is_valid():
			f = form.save(commit=False)
			f.last_edited_by = request.user
			f.save()
			return HttpResponseRedirect('/a/')
	else:
		form = DocumentForm(instance=doc)
	return render_to_response('add.html', {
		'form': form,
	}, context_instance=RequestContext(request))

apps/userprofile/views.py
from django.template import RequestContext
from django.http import HttpResponseForbidden
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages

from userprofile.models import UserProfile
from userprofile.forms import UserProfileForm

def index(request):
	users = User.objects.all()
	
	return render_to_response('userprofile/index.html', {
		'users': users,
	}, context_instance=RequestContext(request))

@login_required
def update_user_profile(request, user_id):
	user = get_object_or_404(User, pk=user_id)

	if request.user == user or request.user.is_superuser:
		up = UserProfile.objects.get_or_create(user=user, defaults={ 'user' : user })
		userprofile = up[0]
		
		if request.method == 'POST':
			f = UserProfileForm(request.POST, instance=userprofile)
			if f.is_valid():
				try:
					f.save()
				except:
					messages.error(request,'There was a problem updating the user profile.')
				else:
					messages.success(request,'User profile updated successfully!.')
		f = UserProfileForm(instance=userprofile)
	
		return render_to_response('userprofile/update_user_profile.html', {
			'form': f,
		}, context_instance =  RequestContext(request))
	else:
		return HttpResponseForbidden('You do not have access to this page.')

templates/_template.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block extra_css %}
<style>
</style>
{% endblock %}

{% block extra_js %}
<script>
	$().ready(function() {
	
	});
</script>
{% endblock %}

{% block header %}
	<h2>Home Page</h2>
{% endblock %}

{% block main %}
	<h3>Home Page Content</h3>
	<p>Oh hai</p>
{% endblock %}

templates/add.html
{% extends "base.html" %}

{% block title %}All documents{% endblock %}

{% block extra_css %}{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function(){
	$('#id_document').focus();
	$('#id_document').change(function() {
		var newname = $('#id_document').val().replace('C:\\fakepath\\','').replace('.pdf','').split(/[_]+/).pop();
		newname = newname.replace('.',' (')
		$('#id_title').val(newname+')');
		$('#id_title').focus();
	});
});
</script>
{% endblock %}

{% block header %}
	<h2>Add a new document</h2>
{% endblock %}

{% block main %}
	<form action="" method="POST" enctype="multipart/form-data">
		{{form.as_p}}
		<input type="submit" name="submit" value="Submit" />
	</form>
{% endblock %}

templates/base.html
<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>	   <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>	   <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>ISI Docs - {% block title %}Page Title{% endblock %}</title>
	<meta name="description" content="">
	<meta name="author" content="">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{{ MEDIA_URL }}images/favicon.ico">
	<link rel="apple-touch-icon" href="{{ MEDIA_URL }}images/apple-touch-icon.png">
	
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/style.css?v=2">
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/docs.css">
	<script type="text/javascript"  src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript"  src="{{ MEDIA_URL }}js/zclip/jquery.zclip.min.js"></script>
	
	{% block extra_css %}
	{% endblock %}
</head>

<body>
	
	{% if messages %}
	    <ul class="messages">
	        {% for message in messages %}
	            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	        {% endfor %}
	    </ul>
	{% endif %}

	<div id="container">
		<header>
			<h1><a href="/">IFSI Docs</a></h1>
			<nav>
				<ul>
					{% if request.user.is_authenticated %}
					<li><a href="{% url doc_list %}">All Documents</a></li>
					<li><a href="{% url doc_add %}">Add Document</a></li>
					<li><a href="{% url logout %}">Log Out</a></li>
					{% else %}
					<li><a href="{% url login %}">Log In</a></li>
					{% endif %}
				</ul>
			</nav>
			{% block header %}{% endblock %}
		</header>
		
		<div id="main" role="main">
			{% block main %}
				<h2>Main Content</h2>
			{% endblock %}
		</div> <!-- eo #main -->
		<footer>
			{% block footer %}
				IFSI &copy; Copyright {% now "Y" %}
			{% endblock %}
		</footer>
	</div> <!-- eo #container -->

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js"></script>
	<script>window.jQuery || document.write("<script src='{{ MEDIA_URL }}js/libs/jquery-1.5.1.min.js'>\x3C/script>")</script>

	<!--[if lt IE 7 ]>
	  <script src="{{ MEDIA_URL }}js/libs/dd_belatedpng.js"></script>
	  <script>DD_belatedPNG.fix("img, .png_bg");</script>
	<![endif]-->

	<script>
	  var _gaq=[["_setAccount","UA-XXXXX-X"],["_trackPageview"]]; // Change UA-XXXXX-X to be your site's ID 
	  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	  g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
	  s.parentNode.insertBefore(g,s)}(document,"script"));
	</script>
	
	{% block extra_js %}
	{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block extra_css %}{% endblock %}

{% block extra_js %}{% endblock %}

{% block header %}
	<h2>Log in to access documents</h2>
{% endblock %}

{% block main %}{% endblock %}

templates/list.html
{% extends "base.html" %}

{% block title %}All documents{% endblock %}

{% block extra_css %}{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function(){
    $(".copy").zclip({
        path: "{{MEDIA_URL}}js/zclip/ZeroClipboard.swf",
        copy: window.location.href,
        afterCopy:function(){
            alert("Squad URL copied to clipboard.");
        }
    });
});
</script>
{% endblock %}

{% block header %}
	<h2>All documents</h2>
{% endblock %}

{% block main %}
	<table style="width: 90%;">
		<tr>
			<th>Document Name</th>
			<th>Cat</th>
			<th>Filename</th>
			<th>Copy</th>
			<th>Created By</th>
			<th style="width: 10%;">Last</th>
			<th>Modified On</th>
			<th>Edit</th>
		</tr>
	{% for d in documents %}
		<tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
			<td>{{d.title}}</td>
			<td class="center">{{d.category.name}}</td>
			<td><a href="/d/{{d.id}}">{{d.filename}}</a></td>
			<td><a class="copy" title="/d/{{d.id}}" href="javascript:;">Copy</a></td>
			<td class="center">{{d.creator}}</td>
			<td class="center">{{d.last_edited_by}}</td>
			<td>{{d.last_modified}}</td>
			<td ><a href="{% url doc_edit %}{{d.id}}">Edit</a></td>
		</tr>
	{% endfor %}
	</table>
{% endblock %}

templates/userprofile/index.html
{% extends "base.html" %}

{% block title %}Sample Index{% endblock %}

{% block extra_css %}
<style>
</style>
{% endblock %}

{% block extra_js %}
<script>
	$().ready(function() {
	
	});
</script>
{% endblock %}

{% block header %}
	<h2>Sample Index</h2>
{% endblock %}

{% block main %}
	<h2>Sample Index Content</h2>
	<p>Oh hai</p>
{% endblock %}

templates/userprofile/update_user_profile.html
{% extends "base.html" %}

{% block title %}Update User Profile{% endblock %}

{% block extra_css %}
<style>
</style>
{% endblock %}

{% block extra_js %}
<script>
	$().ready(function() {
	
	});
</script>
{% endblock %}

{% block header %}
	<h2>User Profile</h2>
{% endblock %}

{% block main %}
	<h3>Update User Profile</h3>
	<form name="update_user_profile" action="{% url update_user_profile user.pk %}" method="POST">
		{{ form.as_p }}
		<input type="submit" />
	</form>
{% endblock %}